version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: playtopia_mysql
    ports:
      - "3306:3306"  
    environment:
      MYSQL_DATABASE: playtopia_db    
      MYSQL_USER: admin                
      MYSQL_PASSWORD: admin            
      MYSQL_ROOT_PASSWORD: rootpassword 
    volumes:
      - mysql_data:/var/lib/mysql     

volumes:
  mysql_data:                        
